// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext;

namespace QPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(QPlanningApplicationContext))]
    [Migration("20200311195247_correctSpelling")]
    partial class correctSpelling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Achternaam = "Mengelers",
                            ConcurrencyStamp = "76259dc1-3249-4575-8383-b51080a86678",
                            Email = "roy.mengelers@zuyd.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "roy.mengelers@zuyd.nl",
                            NormalizedUserName = "roy.mengelers@zuyd.nl",
                            PasswordHash = "AQAAAAEAACcQAAAAEFESN0Cz+aW9167IZhdWmG6MwvYdZyxSY7JbKYbvbbIOaOGSmZx8KVEuzAO6S/uypA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "roy.mengelers@zuyd.nl",
                            Voornaam = "Roy"
                        });
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Boeking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Boekjaar")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EersteDagVanDeWeek")
                        .HasColumnType("int");

                    b.Property<int?>("IndirecteUrenId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIndirect")
                        .HasColumnType("bit");

                    b.Property<int?>("Jaar")
                        .HasColumnType("int");

                    b.Property<int?>("KlantId")
                        .HasColumnType("int");

                    b.Property<int?>("Maand")
                        .HasColumnType("int");

                    b.Property<int>("MedewerkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MoetNogGeplandWorden")
                        .HasColumnType("bit");

                    b.Property<int?>("OpdrachtId")
                        .HasColumnType("int");

                    b.Property<int>("Uren")
                        .HasColumnType("int");

                    b.Property<int?>("Weeknummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndirecteUrenId");

                    b.HasIndex("KlantId");

                    b.HasIndex("MedewerkerId");

                    b.HasIndex("OpdrachtId");

                    b.ToTable("Boeking","dbo");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Boekjaar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jaar")
                        .HasColumnType("int");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Boekjaar","dbo");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.IndirecteUren", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndirecteUren","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Feestdag"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Interne Projecten"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Overig"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Parttime"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Regulier verlof"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Studie"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Ziek"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Vaktechniek"
                        });
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Einddatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedewerkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerantwoordelijkTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerId");

                    b.HasIndex("VerantwoordelijkTeamId");

                    b.ToTable("Klant","dbo");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.KlantPlanbaarDoorTeams", b =>
                {
                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("KlantId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("KlantPlanbaarDoorTeams","dbo");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Logging.CustomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestJsonObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomLogging","logging");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Logging.ExceptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContextUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionLogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestHost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLogging","logging");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Medewerker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("InternTarief")
                        .HasColumnType("int");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<int?>("MedewerkerFunctieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tarief")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TussenVoegsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MedewerkerFunctieId");

                    b.HasIndex("TeamId");

                    b.ToTable("Medewerker","dbo");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.MedewerkerFunctie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnischeNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedewerkerFunctie","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Deze persoon heeft de functie Partner",
                            DisplayName = "Partner",
                            TechnischeNaam = "Partner"
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Deze persoon heeft de functie Manager",
                            DisplayName = "Manager",
                            TechnischeNaam = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Beschrijving = "Deze persoon heeft de functie AssistantManager",
                            DisplayName = "Assistant manager",
                            TechnischeNaam = "AssistantManager"
                        },
                        new
                        {
                            Id = 4,
                            Beschrijving = "Deze persoon heeft de functie SeniorAssosiate",
                            DisplayName = "Senior assosiate",
                            TechnischeNaam = "SeniorAssosiate"
                        },
                        new
                        {
                            Id = 5,
                            Beschrijving = "Deze persoon heeft de functie Associate",
                            DisplayName = "Associate",
                            TechnischeNaam = "Associate"
                        },
                        new
                        {
                            Id = 6,
                            Beschrijving = "Deze persoon heeft de functie Stagiair",
                            DisplayName = "Stagiair",
                            TechnischeNaam = "Stagiair"
                        },
                        new
                        {
                            Id = 7,
                            Beschrijving = "Inhuur van een persoon, dit kan ook vanuit een ander team zijn",
                            DisplayName = "Inhuur",
                            TechnischeNaam = "Inhuur"
                        },
                        new
                        {
                            Id = 8,
                            Beschrijving = "Inhuur van een Externe functie",
                            DisplayName = "Extern",
                            TechnischeNaam = "Extern"
                        },
                        new
                        {
                            Id = 9,
                            Beschrijving = "Inhuur van een IT functie",
                            DisplayName = "IT Digle",
                            TechnischeNaam = "IT"
                        },
                        new
                        {
                            Id = 10,
                            Beschrijving = "Dit is een tijdelijke toekenning waarna een definitieve kan volgen",
                            DisplayName = "PlaceHolder",
                            TechnischeNaam = "PlaceHolder"
                        });
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Opdracht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Opdracht","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Interim"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Balanscontrole"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Inventarisatie"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Omschrijving = "Overig"
                        });
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Naam = "Limburg"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Naam = "Healthcare"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Naam = "Den Bosch"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "RM",
                            IsActief = true,
                            Modified = new DateTime(2019, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "RM",
                            Naam = "Rotterdam"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QPlanning.Infrastructure.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Boeking", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.IndirecteUren", "IndirecteUren")
                        .WithMany()
                        .HasForeignKey("IndirecteUrenId");

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Opdracht", "Opdracht")
                        .WithMany()
                        .HasForeignKey("OpdrachtId");
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Boekjaar", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Klant", null)
                        .WithMany("Boekjaren")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Klant", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Medewerker", "Partner")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Team", "VerantwoordelijkTeam")
                        .WithMany()
                        .HasForeignKey("VerantwoordelijkTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.KlantPlanbaarDoorTeams", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Klant", "Klant")
                        .WithMany("PlanbaarDoorTeams")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Team", "Team")
                        .WithMany("PlanbaarDoorTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Medewerker", b =>
                {
                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.MedewerkerFunctie", "MedewerkerFunctie")
                        .WithMany()
                        .HasForeignKey("MedewerkerFunctieId");

                    b.HasOne("QPlanning.Infrastructure.Data.EntityFramework.QPlanningContext.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
